-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    "userID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fullname text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default" NOT NULL,
    phone text COLLATE pg_catalog."default",
    usertype text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    profile_pic text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    address text COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY ("userID")
)

-- Table: public.vehicle

-- DROP TABLE IF EXISTS public.vehicle;

CREATE TABLE IF NOT EXISTS public.vehicle
(
    "carID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "carName" text COLLATE pg_catalog."default",
    "carImage" text COLLATE pg_catalog."default",
    model text COLLATE pg_catalog."default",
    "numberPlate" text COLLATE pg_catalog."default",
    make text COLLATE pg_catalog."default",
    category text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    "userID" integer,
    "seatNo" integer,
    CONSTRAINT "Cars_pkey" PRIMARY KEY ("carID"),
    CONSTRAINT user_id_fk FOREIGN KEY ("userID")
        REFERENCES public.users ("userID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)


-- Table: public.messege

-- DROP TABLE IF EXISTS public.messege;

CREATE TABLE IF NOT EXISTS public.messege
(
    _id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "senderId" integer,
    message text COLLATE pg_catalog."default",
    "userIsSender" boolean,
    status text COLLATE pg_catalog."default",
    "createdAt" date,
    "receiverId" integer,
    "conversationId" text COLLATE pg_catalog."default",
    CONSTRAINT messege_pkey PRIMARY KEY (_id)
)

-- Table: public.booking

-- DROP TABLE IF EXISTS public.booking;

CREATE TABLE IF NOT EXISTS public.booking
(
    userid integer NOT NULL,
    carid integer NOT NULL,
    pickup_date timestamp with time zone NOT NULL,
    dropoff_date timestamp with time zone NOT NULL,
    bk_status text COLLATE pg_catalog."default",
    seat_available integer,
    co_passenger integer[],
    "bookingID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT booking_pk PRIMARY KEY ("bookingID"),
    CONSTRAINT "Booking_carID_fkey" FOREIGN KEY (carid)
        REFERENCES public.vehicle ("carID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Booking_userID_fkey" FOREIGN KEY (userid)
        REFERENCES public.users ("userID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)







